/* Browser acceptance uses synthetic data intercepted in memory, never a release file. */
const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || "playwright");
require("../stats.js");
const { validate, analyze } = globalThis.RhodesStats;
const base = process.env.SITE_TEST_URL || "http://127.0.0.1:4173";
const output = path.join(__dirname, "../test-results");
fs.mkdirSync(output, { recursive: true });
const characters = ["甲", "乙", "丙", "丁", "戊", "己", "庚", "零"].map((name, i) => ({ id: "c" + i, name: "测试" + name, aliases: i === 0 ? ["别名甲"] : [] }));
const episodes = ["001_测试篇", "057_测试篇", "058_测试篇", "059_测试篇"].map((name, i) => ({ id: "e" + i, name, order: i + 1, cast_character_ids: [["c0"], ["c0", "c1"], ["c2"], []][i], official_url: "https://comic.hypergryph.com/comic/6253/test-" + i }));
const instances = [];
function add(c, e, count) { for (let i = 0; i < count; i++) instances.push({ id: "i" + instances.length, character_id: "c" + c, episode_id: "e" + e, image_id: "image" + e, crop_url: "/media/crops/test.webp", source_preview_url: "/media/source-previews/test.webp", sort_key: String(instances.length).padStart(3, "0") }); }
add(0, 0, 39); add(0, 1, 1); add(1, 0, 1); add(1, 1, 3); add(2, 0, 1); add(2, 2, 1); add(3, 1, 1); add(4, 1, 1); add(5, 2, 1); add(6, 3, 1);
const data = { release_id: "synthetic-test-only", generated_at: "2026-09-23T00:00:00Z", characters, episodes, instances, cast_complete: true };
const a = analyze(validate(data));
assert.equal(instances.length, 50);
assert.equal(a.imageCount, 4);
assert.equal(a.characters.get("c0").count, 40);
assert.equal(a.characters.get("c0").episodes.size, 2);
assert.equal(a.commonPairs.find(p => p.first === "c0" && p.second === "c1").count, 2);
assert.equal(a.records[0].count, 39);
assert.equal(a.rankings.rare[0].count, 1);
assert(!a.rankings.rare.some(c => c.id === "c7"));
assert.equal(a.characters.get("c1").cameo, 1);
assert.equal(a.characters.get("c0").cameo, 0);
assert.equal(a.rankings.noHome.length, 4);
assert.equal(a.characters.get("c0").absence, 2);
assert.equal(a.chart.reduce((n, c) => n + c.count, 0), 50);
assert.equal(analyze(validate({ ...data, cast_complete: false })).rankings.cameo, null);
assert.equal(analyze(validate({ ...data, episodes: episodes.map(e => ({ ...e, order: undefined })) })).rankings.absence, null);
assert.throws(() => validate({ ...data, instances: [...instances, instances[0]] }));
assert.throws(() => validate({ ...data, instances: [{ ...instances[0], crop_url: "https://example.com/tracking.png" }] }));
assert.throws(() => validate({ ...data, episodes: [{ ...episodes[0], official_url: "javascript:alert(1)" }] }));
console.log("Statistics: counts, deduplication, cast, chronology, validation passed");

(async () => {
  const browser = await chromium.launch({ headless: true, executablePath: process.env.CHROMIUM_EXECUTABLE, args: ["--no-sandbox"] });
  try {
    const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
    const errors = [];
    const page = await context.newPage();
    page.on("pageerror", e => errors.push(e.message));
    page.on("console", message => { if (/violates.*(?:Security|policy)|Refused to/i.test(message.text())) errors.push(message.text()); });
    const csp = fs.readFileSync(path.join(__dirname, "../_headers"), "utf8").split("\n").find(line => line.includes("Content-Security-Policy:")).split("Content-Security-Policy: ")[1];
    await page.route(base + "/**", async route => {
      if (route.request().resourceType() !== "document") return route.continue();
      const response = await route.fetch();
      return route.fulfill({ response, headers: { ...response.headers(), "content-security-policy": csp } });
    });
    await page.goto(base);
    await page.waitForFunction(() => document.querySelector("#search-status").textContent.includes("还没上架"));
    assert.equal(await page.locator("#totals strong").allTextContents().then(x => x.join(",")), "—,—,—,—");
    await page.screenshot({ path: output + "/desktop-empty.png", fullPage: true });
    const svg = '<svg xmlns="http://www.w3.org/2000/svg" width="180" height="180"><rect x="10" y="10" width="160" height="160" rx="45" fill="#d7c7ee"/><circle cx="65" cy="75" r="7" fill="#665078"/><circle cx="115" cy="75" r="7" fill="#665078"/><path d="M70 115 Q90 135 110 115" stroke="#665078" stroke-width="5" fill="none"/></svg>';
    await page.route("**/media/**", route => route.fulfill({ contentType: "image/svg+xml", body: svg }));
    await page.route("**/data/release.json", route => route.fulfill({ json: data }));
    await page.reload();
    await page.waitForFunction(() => document.querySelector("#totals strong").textContent === "4");
    assert.deepEqual(await page.locator("#totals strong").allTextContents(), ["4", "50", "8", "4"]);
    assert.equal(await page.locator(".legend-row").count(), 6);
    assert(await page.locator("#results-section").isHidden());
    await page.screenshot({ path: output + "/desktop-data.png", fullPage: true });
    await page.locator("#site-search").fill("别名甲"); await page.locator("#site-search").press("Enter");
    assert.equal(await page.locator("#result-count").textContent(), "40 张表情");
    assert.equal(await page.locator(".expression-card").count(), 36);
    await page.locator("#load-more").click();
    assert.equal(await page.locator(".expression-card").count(), 40);
    await page.locator(".expression-card").first().hover();
    await page.locator(".source-peek img").first().waitFor({ state: "visible", timeout: 5000 });
    assert(await page.locator(".source-peek img").first().isVisible(), "Desktop hover must show original-source preview");
    await page.locator("#site-search").fill("57"); await page.locator('[data-mode="episodes"]').click();
    assert.equal(await page.locator("#site-search").inputValue(), "57");
    assert.equal(await page.locator(".episode-card").count(), 1);
    await page.locator(".episode-cover").click();
    assert.equal(await page.locator("#result-count").textContent(), "6 张表情");
    assert((await page.locator(".crop-wrap").first().getAttribute("href")).includes("test-1"));
    await page.reload();
    await page.waitForSelector(".expression-card");
    assert.equal(await page.locator("#result-count").textContent(), "6 张表情");
    await page.goBack();
    await page.waitForSelector(".episode-card");
    await page.locator("#ranking-kind").selectOption("rare");
    assert(!(await page.locator("#character-ranking").textContent()).includes("测试零"));
    await page.locator("#pair-ranking .rank-row").first().click();
    assert.equal(await page.locator("#result-count").textContent(), "44 张表情");
    await page.locator("#record-ranking .rank-row").first().click();
    assert.equal(await page.locator("#result-count").textContent(), "39 张表情");
    await page.locator("#clear-search").click();
    assert(await page.locator("#results-section").isHidden());
    await page.locator("#ribbon-pause").click();
    assert.equal(await page.locator("#ribbon-pause").getAttribute("aria-pressed"), "true");
    await page.locator("#ribbon").hover(); await page.locator("#site-search").hover();
    assert.equal(await page.locator("#ribbon-pause").getAttribute("aria-pressed"), "true", "Hover leave must not cancel user's pause");
    await page.emulateMedia({ reducedMotion: "reduce" });
    await page.waitForFunction(() => document.querySelector("#ribbon-pause").disabled);
    assert(await page.locator("#ribbon-pause").isDisabled());
    await page.locator("#ribbon-next").click();
    await page.setViewportSize({ width: 390, height: 844 });
    await page.goto(base);
    await page.waitForSelector(".legend-row");
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.screenshot({ path: output + "/mobile-data.png", fullPage: true });
    await page.locator("#site-search").fill("别名甲"); await page.locator("#site-search").press("Enter");
    await page.locator(".source-toggle").first().click();
    await page.locator(".source-peek img").first().waitFor({ state: "visible", timeout: 5000 });
    assert(await page.locator(".source-peek img").first().isVisible());
    assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    await page.keyboard.press("Escape");
    assert.equal(await page.locator(".expression-card.preview-open").count(), 0);
    await page.route("**/data/release.json", route => route.fulfill({ json: { ...data, cast_complete: false, episodes: episodes.map(e => ({ ...e, order: undefined })) } }));
    await page.goto(base);
    await page.waitForSelector(".legend-row"); await page.locator("#ranking-kind").selectOption("cameo");
    assert((await page.locator("#character-ranking").textContent()).includes("本篇角色资料"));
    await page.locator("#ranking-kind").selectOption("absence");
    assert((await page.locator("#character-ranking").textContent()).includes("篇目顺序"));
    await page.route("**/data/release.json", route => route.fulfill({ status: 500, body: "error" }));
    await page.reload(); await page.waitForSelector("#retry");
    await page.route("**/data/release.json", route => route.fulfill({ json: data }));
    await page.locator("#retry").click(); await page.waitForSelector(".legend-row");
    await page.route("**/data/release.json", route => route.fulfill({ json: { invalid: true } }));
    await page.reload(); await page.waitForSelector("#retry");
    for (const name of ["about", "privacy", "404"]) {
      await page.goto(base + "/" + name + ".html");
      assert(await page.locator("h1").isVisible());
      assert.equal(await page.locator(".site-header nav a").count(), 3);
      assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
    }
    assert.deepEqual(errors, []);
    console.log("Browser: desktop/mobile, CSP, unified search, aliases, episode numbers, paging, preview, reload/back, rankings, missing metadata, carousel, error/retry passed");
  } finally { await browser.close(); }
})().catch(e => { console.error(e); process.exitCode = 1; });
