#!/usr/bin/env python3
"""Compile editable copy and templates; no dependencies or private data access."""
import argparse
import hashlib
import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def unique_pairs(pairs):
    result = {}
    for key, value in pairs:
        if key in result:
            raise ValueError('Duplicate copy key: ' + key)
        result[key] = value
    return result


def build(check=False):
    source = (ROOT / 'content/copy.zh-CN.json').read_text(encoding='utf-8')
    entries = json.loads(source, object_pairs_hook=unique_pairs)
    copy = {}
    for key, entry in entries.items():
        if not isinstance(entry.get('text'), str) or not entry.get('note'):
            raise ValueError('Each entry needs text and note: ' + key)
        slots = set(re.findall(r'\{(\w+)\}', entry['text']))
        if slots != set(entry.get('slots', [])):
            raise ValueError('Preserve placeholders for ' + key)
        copy[key] = entry['text']
    for name in ('app.js', 'stats.js'):
        script = (ROOT / name).read_text(encoding='utf-8')
        for key in re.findall(r'\bt\("([\w.]+)"\s*[,)]', script):
            if key not in copy:
                raise ValueError('Missing script copy: ' + key)
    version = hashlib.sha256((source + ''.join((ROOT / name).read_text(encoding='utf-8')
                            for name in ('styles.css', 'app.js', 'stats.js'))).encode()).hexdigest()[:12]
    values = dict(copy, asset_version=version)
    payload = json.dumps(copy, ensure_ascii=False).replace('<', '\\u003c').replace('>', '\\u003e').replace('&', '\\u0026')
    outputs = {}
    for name in ('index', 'about', 'privacy', '404'):
        template = (ROOT / ('templates/' + name + '.html')).read_text(encoding='utf-8')
        template = re.sub(r'\{\{>(\w+)\}\}', lambda m: (ROOT / ('templates/partials/' + m[1] + '.html')).read_text(encoding='utf-8'), template)
        template = re.sub(r'\{\{([\w.]+)\}\}', lambda m: payload if m[1] == 'copy_json' else html.escape(values[m[1]], quote=True), template)
        outputs[name + '.html'] = '<!-- Generated by tools/build.py; edit content/ or templates/. -->\n' + template
    changed = []
    for name, text in outputs.items():
        path = ROOT / name
        if not path.exists() or path.read_text(encoding='utf-8') != text:
            changed.append(name)
            if not check:
                path.write_text(text, encoding='utf-8')
    if check and changed:
        raise SystemExit('Run python3 tools/build.py: ' + ', '.join(changed))
    print(('Verified' if check else 'Built') + ' ' + ', '.join(outputs) + ' (' + str(len(copy)) + ' copy entries)')


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    build(parser.parse_args().check)
